"""Generate reviewable k6 artifacts from a PerfAgent plan."""

from __future__ import annotations

import json
import re
from pathlib import Path

from openharness.agents.perf_agent.models import (
    GeneratedK6File,
    K6GenerationResult,
    PerformancePlan,
    PerformanceScenario,
)


def generate_k6_artifacts(plan: PerformancePlan, output_dir: str | Path) -> K6GenerationResult:
    destination = Path(output_dir).expanduser().resolve()
    destination.mkdir(parents=True, exist_ok=True)

    files: list[GeneratedK6File] = []
    warnings = list(plan.warnings)

    for scenario in plan.scenarios:
        filename = _script_filename(scenario.name)
        script_path = destination / filename
        script_path.write_text(_render_k6_script(plan, scenario), encoding="utf-8")
        files.append(
            GeneratedK6File(
                path=script_path.as_posix(),
                kind="k6_script",
                scenario_name=scenario.name,
            )
        )

    config_path = destination / "config.json"
    config_path.write_text(
        json.dumps(_render_config(plan), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    files.append(GeneratedK6File(path=config_path.as_posix(), kind="config"))

    readme_path = destination / "README.md"
    readme_path.write_text(_render_readme(plan), encoding="utf-8")
    files.append(GeneratedK6File(path=readme_path.as_posix(), kind="readme"))

    if not plan.scenarios:
        warnings.append("No k6 scenario scripts were generated because the plan has no scenarios.")

    return K6GenerationResult(
        output_dir=destination.as_posix(),
        base_url_env=plan.base_url_env,
        files=files,
        warnings=warnings,
    )


def _render_k6_script(plan: PerformancePlan, scenario: PerformanceScenario) -> str:
    thresholds = {
        threshold.metric: [threshold.condition]
        for threshold in scenario.thresholds
    }
    method = scenario.method.lower()
    scenario_key = _safe_identifier(scenario.name)
    request_lines = _request_lines(method, scenario.path)
    payload_block = (
        "  const payload = { example: true };\n"
        if method in {"post", "put", "patch", "delete"}
        else ""
    )

    return "\n".join(
        [
            "import http from 'k6/http';",
            "import { check, sleep } from 'k6';",
            "",
            f"const BASE_URL = __ENV.{plan.base_url_env} || 'http://localhost:8000';",
            "",
            "export const options = {",
            "  scenarios: {",
            f"    {scenario_key}: {{",
            "      executor: 'ramping-vus',",
            "      stages: [",
            f"        {{ duration: '{scenario.load_profile.ramp_up}', "
            f"target: {scenario.load_profile.virtual_users} }},",
            f"        {{ duration: '{scenario.load_profile.duration}', "
            f"target: {scenario.load_profile.virtual_users} }},",
            "        { duration: '30s', target: 0 },",
            "      ],",
            "    },",
            "  },",
            "  thresholds: "
            + _indent_multiline(json.dumps(thresholds, indent=2), spaces=2).lstrip()
            + ",",
            "};",
            "",
            "export default function () {",
            "  const params = {",
            "    headers: {",
            "      'Content-Type': 'application/json',",
            "    },",
            "  };",
            payload_block.rstrip(),
            *request_lines,
            "  check(response, {",
            "    'status is not 5xx': (res) => res.status < 500,",
            "  });",
            "  sleep(1);",
            "}",
            "",
        ]
    ).replace("\n\n  const response", "\n  const response")


def _render_config(plan: PerformancePlan) -> dict[str, object]:
    return {
        "base_url_env": plan.base_url_env,
        "repository_root": plan.repository_root,
        "repo_agent_config": plan.repo_agent_config,
        "generated_from": plan.generated_from,
        "scenarios": [
            {
                "name": scenario.name,
                "script": _script_filename(scenario.name),
                "scenario_key": _safe_identifier(scenario.name),
                "method": scenario.method,
                "path": scenario.path,
                "priority": scenario.priority,
                "source": scenario.source,
                "framework": scenario.framework,
            }
            for scenario in plan.scenarios
        ],
    }


def _render_readme(plan: PerformancePlan) -> str:
    first_script = _script_filename(plan.scenarios[0].name) if plan.scenarios else "scenario.js"
    lines = [
        "# OpenHarness k6 Artifacts",
        "",
        "Generated by PerfAgent from RepoAgent performance targets.",
        "",
        "These scripts are reviewable artifacts. They are not executed automatically.",
        "",
        "## Run",
        "",
        "```bash",
        f"export {plan.base_url_env}=http://localhost:8000",
        f"k6 run {first_script}",
        "```",
        "",
        "Review authentication, test data, and target environment before running.",
        "",
        "## Scenarios",
        "",
    ]

    if plan.scenarios:
        lines.extend(
            f"- `{_script_filename(scenario.name)}`: {scenario.method} {scenario.path}"
            for scenario in plan.scenarios
        )
    else:
        lines.append("- No scenario scripts were generated.")

    return "\n".join(lines) + "\n"


def _safe_filename(name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_.-]+", "_", name)
    cleaned = re.sub(r"_+", "_", cleaned).strip("._")
    return cleaned or "scenario"


def _script_filename(name: str) -> str:
    return f"{_safe_filename(name)}.js"


def _safe_identifier(name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_$]+", "_", name)
    cleaned = re.sub(r"_+", "_", cleaned).strip("_")
    if not cleaned:
        return "scenario"
    if cleaned[0].isdigit():
        return f"scenario_{cleaned}"
    return cleaned


def _request_lines(method: str, path: str) -> list[str]:
    if method == "get":
        return [f"  const response = http.get(`${{BASE_URL}}{path}`, params);"]

    return [
        f"  const response = http.{method}(",
        f"    `${{BASE_URL}}{path}`,",
        "    JSON.stringify(payload),",
        "    params,",
        "  );",
    ]


def _indent_multiline(value: str, spaces: int) -> str:
    prefix = " " * spaces
    return "\n".join(f"{prefix}{line}" for line in value.splitlines())
